// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authToken.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (client_id, token, ip, user_agent, created_at)
VALUES ($1, $2, $3, $4, NOW())
`

type CreateAuthTokenParams struct {
	ClientID  int32       `json:"clientId"`
	Token     pgtype.UUID `json:"token"`
	Ip        string      `json:"ip"`
	UserAgent pgtype.Text `json:"userAgent"`
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.Exec(ctx, createAuthToken,
		arg.ClientID,
		arg.Token,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const findAuthToken = `-- name: FindAuthToken :one
SELECT token
FROM auth_tokens
WHERE client_id = $1 AND (ip = $2 OR user_agent = $3)
`

type FindAuthTokenParams struct {
	ClientID  int32       `json:"clientId"`
	Ip        string      `json:"ip"`
	UserAgent pgtype.Text `json:"userAgent"`
}

func (q *Queries) FindAuthToken(ctx context.Context, arg FindAuthTokenParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAuthToken, arg.ClientID, arg.Ip, arg.UserAgent)
	var token pgtype.UUID
	err := row.Scan(&token)
	return token, err
}
