// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: client.sql

package sqlc

import (
	"context"
)

const createClient = `-- name: CreateClient :one
INSERT INTO clients (email, login, password_hash)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateClientParams struct {
	Email        string `json:"email"`
	Login        string `json:"login"`
	PasswordHash string `json:"passwordHash"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (int32, error) {
	row := q.db.QueryRow(ctx, createClient, arg.Email, arg.Login, arg.PasswordHash)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const findClientByIdentifier = `-- name: FindClientByIdentifier :one
SELECT
    id as client_id,
    password_hash
FROM clients
WHERE login = $1 OR email = $1
LIMIT 1
`

type FindClientByIdentifierRow struct {
	ClientID     int32  `json:"clientId"`
	PasswordHash string `json:"passwordHash"`
}

func (q *Queries) FindClientByIdentifier(ctx context.Context, login string) (FindClientByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, findClientByIdentifier, login)
	var i FindClientByIdentifierRow
	err := row.Scan(&i.ClientID, &i.PasswordHash)
	return i, err
}
