// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthToken struct {
	ID        int32            `json:"id"`
	ClientID  int32            `json:"clientId"`
	Token     pgtype.UUID      `json:"token"`
	Ip        string           `json:"ip"`
	UserAgent pgtype.Text      `json:"userAgent"`
	CreatedAt pgtype.Timestamp `json:"createdAt"`
}

type Client struct {
	ID           int32  `json:"id"`
	Email        string `json:"email"`
	Login        string `json:"login"`
	PasswordHash string `json:"passwordHash"`
}

type Track struct {
	ID         int32          `json:"id"`
	UploaderID pgtype.Int4    `json:"uploaderId"`
	ImageID    pgtype.Int4    `json:"imageId"`
	Path       string         `json:"path"`
	Duration   pgtype.Numeric `json:"duration"`
	Title      string         `json:"title"`
	Album      pgtype.Text    `json:"album"`
	Codec      pgtype.Text    `json:"codec"`
	Bitrate    pgtype.Int4    `json:"bitrate"`
	Lossless   bool           `json:"lossless"`
}

type TrackImage struct {
	ID          int32  `json:"id"`
	Path        string `json:"path"`
	Hash        string `json:"hash"`
	TracksCount int32  `json:"tracksCount"`
}
