// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error
	CreateClient(ctx context.Context, arg CreateClientParams) (int32, error)
	CreateTrackImage(ctx context.Context, arg CreateTrackImageParams) (int32, error)
	FindAuthToken(ctx context.Context, arg FindAuthTokenParams) (pgtype.UUID, error)
	FindClientByIdentifier(ctx context.Context, login string) (FindClientByIdentifierRow, error)
}

var _ Querier = (*Queries)(nil)
