// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trackImage.sql

package sqlc

import (
	"context"
)

const createTrackImage = `-- name: CreateTrackImage :one
INSERT INTO track_images (path, hash, tracks_count)
VALUES ($1, $2, 0)
RETURNING id
`

type CreateTrackImageParams struct {
	Path string `json:"path"`
	Hash string `json:"hash"`
}

func (q *Queries) CreateTrackImage(ctx context.Context, arg CreateTrackImageParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTrackImage, arg.Path, arg.Hash)
	var id int32
	err := row.Scan(&id)
	return id, err
}
